api: <api-type-place-holder>
symbol: <symbol-place-holder>
interval: <interval-place-holder>
strategy: <strategy-type-place-holder>
indicator: <indicator-type-place-holder>
cash: <cash-place-holder>
commission: <comission-place-holder>